[package]
name = "icrc2-batch"
version = "1.0.0"
description = "Batch functionality for ICRC-2 enabled token ledgers"
repository = "https://github.com/MemeFighterCo/icrc2-batch.git"
keywords = [ "ICRC", "ICRC-2", "transaction", "token", "ledger" ]
license = "MIT"

[dependencies]
testing = "https://github.com/aviate-labs/testing.mo#v0.1.3"
base = "0.11.1"